<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.sanctuary.bs.api.domain.UserTest" tests="8" skipped="0" failures="0" errors="0" timestamp="2022-09-22T23:36:21" hostname="RASHID" time="0.006">
  <properties/>
  <testcase name="givenAnInvalidUniqueIdentifier_whenCallNewUser_thenThrowException()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.002"/>
  <testcase name="givenAnInvalidPassword_whenCallNewUser_thenThrowException()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.0"/>
  <testcase name="givenAnInvalidRole_whenCallNewUser_thenThrowException()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.0"/>
  <testcase name="givenAnInvalidEmail_whenCallNewUser_thenThrowException()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.001"/>
  <testcase name="givenAValidParams_whenCallNewUser_thenInstantiateAUser()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.0"/>
  <testcase name="givenAnInvalidPhoneNumber_whenCallNewUser_thenThrowException()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.0"/>
  <testcase name="givenAValidUser_whenCallUpdateUser_thenShouldReturnUpdatedUser()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.001"/>
  <testcase name="givenAnInvalidName_whenCallNewUser_thenThrowException()" classname="io.sanctuary.bs.api.domain.UserTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
